[package]
name = "nesVM"
version = "0.1.0"
authors = ["ksparker7 <ksparker@ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
